### ISSUE TITLE
multiple css files not written to json file

### ISSUE THREAD

**Issue by ghost** [ztoben/assets-webpack-plugin#78] opened 2017-09-21 08:42 UTC
i'm using extract-text-webpack-plugin to extract 2 css files. assets-webpack-plugin is unfortunately only writing a reference to one of these files in the json. here's the relevant parts of my webpack config...

```
const extractSass = new ExtractTextPlugin({
    filename: 'styles.[contenthash].css'
});
const extractSassGlobal = new ExtractTextPlugin({
    filename: 'styles-global.[contenthash].css'
});
```
then inside `rules`...
```
                test: /\.scss$/,
                use: extractSass.extract({
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                modules: true,
                                localIdentName: '[name]__[local]--[hash:base64:5]'
                            }
                        },
                        {
                            loader: 'sass-loader'
                        }]
                }),
                exclude: [
                    path.resolve(__dirname, './lib/global.scss')
                ]
            },
            {
                test: /global.scss$/,
                use: extractSassGlobal.extract({
                    use: [
                        {
                            loader: 'css-loader'
                        },
                        {
                            loader: 'sass-loader'
                        }
                    ]
                })
            }
```
and in the `plugins` array...
```
plugins: [
        extractSass,
        extractSassGlobal,
        new AssetsPlugin({
            prettyPrint: true
        })
]
```

finally the generated webpack-assets.json with just the one css file reference (it's always the latter of the two specified in the plugins array)

```
{
"app": {
    "js": "app.01423a1f392048ff387e.js",
    "css": "styles-global.450ffe3acbcdb163cd1ee9adfbf0161d.css"
  }
}
```

am i doing something wrong or is this functionality not supported?

**Comment by aaronatmycujoo** [comment] 2017-09-21 12:57
I came here to report the same thing 🤔

I am using a couple of extract text plugin instances and only the last one is getting picked up with the first one's name.

My setup is pretty much exactly the same as yours.

assets-webpack-plugin@^3.2.0
webpack@3.5.5

**Comment by aaronatmycujoo** [comment] 2017-09-25 07:34
The problem is that this plugin only supports one file per filename. You are extracting two css files and so the plugin only picks up the last one.

More information here: https://github.com/kossnocorp/assets-webpack-plugin/issues/72#issuecomment-311157935

I have no idea about a workaround apart from giving the files all unique extensions.

**Comment by aaronatmycujoo** [comment] 2017-09-25 08:02
I've created a PR to solve this (https://github.com/kossnocorp/assets-webpack-plugin/pull/79)

**Comment by ztoben** [comment] 2018-06-13 19:22
Fixed in https://github.com/kossnocorp/assets-webpack-plugin/commit/95d802adfc0c839872d0ba4c689ccd1de41c5918. Thank you!

**Closed as completed by ztoben** 2018-06-13 19:22 UTC
