### ISSUE TITLE
Could not create output folder Error

### ISSUE THREAD

**Issue by Adidi** [ztoben/assets-webpack-plugin#239] opened 2020-07-09 11:19 UTC
**Describe the bug**
getting an error ` in [AssetsWebpackPlugin] Could not create output folder` 

**To Reproduce**
just compile my project does not seem to work because of this error

**Expected behavior**
To work - the output folder is created and the file is there (js bundle file) it just keep throwing this message

**Webpack Config**
```
           entry: ['./src'],
		output: {
			path: path.resolve(__dirname, '../public/dist')
		},
		module: {
			rules: [
				{
					test: /\.tsx?$/,
					exclude: /node_modules/,
					use: tsLoaders
				},
				{
					test: /\.css$/,
					use: styleLoaders
				}
			]
		},
		resolve: {
			...
		},
		plugins: [
			new CleanWebpackPlugin(),
			new webpack.DefinePlugin({
				'process.env.NODE_ENV': JSON.stringify(dev ? 'development' : 'production')
			}),
			new AssetsPlugin({
				filename: 'assets.json',
				useCompilerPath: true,
				includeAllFileTypes: false,
				manifestFirst: true
			})
		]
```
merge with 
```
mode: 'development',
	devtool: 'source-map',
	entry: ['webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000'],
	output: {
		publicPath: '/',
		filename: 'dist/app.js'
	},
	plugins: [new webpack.HotModuleReplacementPlugin()]
```
**Desktop (please complete the following information):**
 - OS:  `Ubuntu 20.04 LTS`
 - Node version: `14.5.0`
 - Plugin version: `5.0.2`

**Comment by ztoben** [comment] 2020-07-09 12:55
Did this change after you updated a version or are you just trying to get it set up for the first time? Since you have `useCompilerPath` set, it's trying to use the output.path value that you have set in the base webpack config.

I'm having a hard time reproducing the error. Using the same config you have and the same output path I get the file generated correctly with no issues. Is there a reason you are building your dist outside of your project folder? Your setup as-is generates the public/dist folder at a level up from the actual root of your project.

**Comment by Adidi** [comment] 2020-07-09 19:30
No. i had this configuration month ago - version `3.9.12` was working for me - only when i upgraded i get this error.
My project is backend and frontend under `lerna` monorepo - so my dist folder is under my project folder - i did not understand how you conclude otherwise sorry

**Comment by ztoben** [comment] 2020-07-09 20:56
Ah, okay that makes sense. But sorry, I can't seem to reproduce with the configuration you've attached so I'm not sure I can help. Are there any other details of your setup that I may be missing?

**Comment by Adidi** [comment] 2020-07-10 06:24
maybe its something with `unbuntu` or/and `node 14` ?

**Comment by ztoben** [comment] 2020-07-10 12:56
Is your project open source? I'd be happy to take a look.

**Comment by Adidi** [comment] 2020-07-11 13:21
No - workplace :) Thanks !

**Comment by ztoben** [comment] 2020-07-22 14:24
Going to close this as I cannot reproduce. If others are having the problem and can help me reproduce I'll re-open.

**Closed as completed by ztoben** 2020-07-22 14:24 UTC
